### ISSUE TITLE
Better UX for copy to clipboard

### ISSUE THREAD

**Issue by jaydson** [braziljs/newsletter-tool#25]
We have the copy to clipboard feature for each category, but it's not well informed.
Perhaps a new icon, tool tip, etc.

![screenshot from 2018-10-07 21-20-21](https://user-images.githubusercontent.com/72206/46588718-0e061a00-ca77-11e8-9d50-6150b2ce7c66.png)

**Comment by JulioGold** [comment]
I added a tooltip to button. #36
