### ISSUE TITLE
Close resolved issues.

### ISSUE THREAD

**Issue by RenatoSiqueira** [braziljs/newsletter-tool#31]
This issues are resolved:
#9
#8 (i think)
#5
#2 
#1

**Comment by jaydson** [comment]
Thanks @RenatoSiqueira !
Let's review:

#9 is resolved
#8 is resolved
#5 is resolved
#2 is not resolved, I just tested here and we still have extra lines
#1 is not resolved, I just tested here and we still have extra spaces
