### ISSUE TITLE
 Remove category from the markdown version 

### ISSUE THREAD

**Issue by jaydson** [braziljs/newsletter-tool#4]
The markdown version is adding the category which is not necessary.

**Comment by JulioGold** [comment]
Where is it? I don't got it

**Comment by jaydson** [comment]
Look at the screenshot @JulioGold 
![screenshot from 2018-10-07 21-12-55](https://user-images.githubusercontent.com/72206/46588626-eb273600-ca75-11e8-96a0-a91c454ba793.png)

Actually, it is not necessary just in the markdown version, it should be removed from all views (HTML, Markdown and Outline)

**Comment by JulioGold** [comment]
I think it's done #35
