### ISSUE TITLE
Ignore comments that are not following the template

### ISSUE THREAD

**Issue by jaydson** [braziljs/newsletter-tool#9]
Every comment which is not following the following template should be ignored:
```
**[Título](URL)**
Rápida descrição
*Categoria*
```

Today we have a lot of unnecessary, because these items are categorized as "Outros".

**Comment by RenatoSiqueira** [comment]
Fixed in PR #27
If not following template, in the weekly.js (with applyMarkdown function) converts this.
With this, resolves Outline error (another issue) and prepare to copy in the Header Markdown option.
All in one! =)
